### ISSUE TITLE
TS2488 error on line 112 of blob-storage.service.ts

### ISSUE THREAD

**Issue by AlphaCreative-Mike** [stottle-uk/stottle-angular-blob-storage#1]
Line 112 is throwing an error in blob-storage.service.ts.  The line reads: 

`scan<T>((items, item) => [...items, item], []),`

The error is:

`"error TS2488: Type 'T' must have a '[Symbol.iterator]()' method that returns an iterator."`

I dropped the blob-storage.service.ts file into my existing Angular 8 app and get that compile error.  I thought maybe it was because my tsconfig was different than yours so I copied yours over and the error persists.  Any thoughts?

Nice sample by the way.

**Comment by stottle-uk** [comment]
Hi @AlphaCreative-Mike 

Thanks for the message, I'm guessing there are some differences in the tsconfig somewhere (maybe in the CLI)

Anyhoo - I've fixed it and pushed 

`scan<T, T[]>((items, item) => [...items, item], []),`

https://github.com/stottle-uk/stottle-angular-blob-storage/commit/6aa3f72fca1d8c867958faa06e9defffa54404b7#diff-65e7b30e92c3981c71f926c5e2cb5985R106

**Comment by AlphaCreative-Mike** [comment]
Awesome.  Thanks!
